# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHoteldouzsamemonth():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hoteldouzsamemonth(self):
    self.driver.get("https://www.tunisiebooking.com/")
    self.driver.set_window_size(960, 946)
    dropdown = self.driver.find_element(By.ID, "ville_des")
    dropdown.find_element(By.XPATH, "//option[. = 'Douz']").click()
    element = self.driver.find_element(By.ID, "ville_des")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "ville_des")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "ville_des")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "check1").click()
    self.driver.find_element(By.LINK_TEXT, "25").click()
    self.driver.find_element(By.LINK_TEXT, "27").click()
    self.driver.find_element(By.ID, "boutonr").click()
    self.driver.execute_script("window.scrollTo(0,250.6666717529297)")
  
