# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDatessamemonth():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_datessamemonth(self):
    self.driver.get("https://www.tunisiebooking.com/")
    self.driver.set_window_size(960, 946)
    self.driver.find_element(By.ID, "check1").click()
    self.driver.find_element(By.LINK_TEXT, "17").click()
    self.driver.find_element(By.LINK_TEXT, "19").click()
    self.driver.find_element(By.ID, "boutonr").click()
    self.driver.execute_script("window.scrollTo(0,276)")
    self.driver.find_element(By.CSS_SELECTOR, "#plus_res > img").click()
  
